/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ConfigData } from "./components/button/button";
export namespace Components {
    interface FcaUiButton {
        "data": ConfigData | string;
        "type": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface FcaUiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFcaUiButtonElement;
}
declare global {
    interface HTMLFcaUiButtonElement extends Components.FcaUiButton, HTMLStencilElement {
    }
    var HTMLFcaUiButtonElement: {
        prototype: HTMLFcaUiButtonElement;
        new (): HTMLFcaUiButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fca-ui-button": HTMLFcaUiButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FcaUiButton {
        "data"?: ConfigData | string;
        "onClicked"?: (event: FcaUiButtonCustomEvent<any>) => void;
        "type"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fca-ui-button": FcaUiButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fca-ui-button": LocalJSX.FcaUiButton & JSXBase.HTMLAttributes<HTMLFcaUiButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
